# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rcarbon2rust_wrappers", use_symbols = TRUE, package_name = "rcarbon2rust")

#' @docType package
#' @usage NULL
#' @useDynLib rcarbon2rust, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)


# nolint end
